language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update && composer install --dev

script: ./Tests/runTests.sh

matrix:
  allow_failures:
    - php: hhvm-nightly
